version: "3.7"

services:
  db:
    container_name: mongo-dev
    image: mongo:4.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_DATABASE=auth
      - MONGO_INITDB_ROOT_PASSWORD=pass
    networks: 
      - cashflow-compose-network
    ports:
      - '27017:27017'
    volumes: 
      - D:\Volumes\MongoDB\data:/data/db
  
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - db
    networks: 
      - cashflow-compose-network
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-dev
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=tribes
    ports:
      - '8081:8081'
    volumes: 
      - D:\Volumes\MongoExpress\data:/data/db

  nats:
    image: 'nats:latest'
    container_name: nats
    networks:
      - cashflow-compose-network    
    ports:
      - '4222:4222'
      - '6222:6222'
      - '8222:8222' 

  cashflow-rc-api:
    build: ./CashFlow.RC.API
    container_name: cashflow-rc-api
    networks:
      - cashflow-compose-network
    depends_on:
      - nats
      - cashflow-rc-wrk
    ports:
      - '15002:15002' 
      
  cashflow-rc-wrk:
    build: .
    container_name: cashflow-rc-wrk
    networks:
      - cashflow-compose-network
    depends_on:
      - nats 
      - db  

networks:
  cashflow-compose-network:
    driver: bridge